#!/bin/bash

# set ARD field with contents of current or last login
# run via ARD 'Send UNIX Command' as 'root' or local admin user

WHOAMI="$(who|awk '/console/ { print $1 }')"

if [ "$WHOAMI" == "" ]; then
 WHOAMI=$(last -1 | awk ' { print $1 } ')
fi

/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -computerinfo -set1 -1 "$WHOAMI"
